### ISSUE TITLE
Question: Does this storage provider automatically handle storing grain references?

### ISSUE THREAD

**Issue by snarlynarwhal** [OrleansContrib/Orleans.StorageProvider.Arango#3]
Does this storage provider automatically handle storing grain references? Say I had a tree data structure in which grains could have a parent and children. Does this provider detect when a property is a grain reference and handle it accordingly, or do I manually need to handle that on Read/Write? I'm new to Orleans.NET so any help understanding this would be much appreciated!

**Comment by richorama** [comment]
Hi @snarlynarwhal,

The provider should serialize grain references correctly. 

The state of your grain will be converted  into JSON, so you should avoid circular references etc...

**Comment by snarlynarwhal** [comment]
Not sure I worded it properly, but to clarify: Does it serialize a reference to the grain, say a grain id, or the entire grain itself as an embedded object? In other terms if A and B each referenced C, would A and B each serialize C as an embedded document creating two distinct instances, or would A and B serialize a reference that pointed to C using the grain id taking advantage of Arango's graph support?

**Comment by richorama** [comment]
Ah, no, it's not that clever!

A grain should only every consider it's own internal state, and not that of other grains.

If a grain's state includes a reference to another grain, then the reference is serialized as a pointer, rather than a copy of a grain.

Arango's graph API is not currently used by the provider.

**Comment by snarlynarwhal** [comment]
Ah darn! Alright, thanks for the help!
